### ISSUE TITLE
Does the "strategy" command work in civicrm mattermost?

### ISSUE THREAD

**Issue by demeritcowboy** [xurizaemon/hubot-bolts#1]
I tried using it yesterday and it didn't do anything:

`@bolts Suggest a strategy for @user`

https://chat.civicrm.org/civicrm/pl/gizthpjxktrwppisnt5tz5fm7o

I was expecting it to offer some kind of zen strategy, like "A curtain does not try to be a teapot."

**Comment by xurizaemon** [comment]
It used to! But I haven't seen it work lately, either.

I'm glad you found this easter egg though 😁 

Perhaps https://obliqueio.herokuapp.com/ was slow that day? I see the endpoint URI is http in this version, but that seems to work still.

**Comment by demeritcowboy** [comment]
Ah it seems to be working now. Yes maybe just some kind of timeout. Thanks will close this.

**Comment by xurizaemon** [comment]
Thanks for asking this, it led me to a couple of other items of interest 😁 

- [Oblique Strategies for Programmers](https://datafire-repos.github.io/oblique-strategies/) ([repo](https://datafire-repos.github.io/oblique-strategies/))
- https://www.azquotes.com/quotes/topics/debugging.html
- [Official printed version](https://www.enoshop.co.uk/product/oblique-strategies.html)
- [Another web-based version](http://stoney.sb.org/eno/oblique.html)
